# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import slate_pb2 as slate__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in slate_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CortexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Focus = channel.unary_unary(
            "/slate.Cortex/Focus",
            request_serializer=slate__pb2.FocusRequest.SerializeToString,
            response_deserializer=slate__pb2.FocusResponse.FromString,
            _registered_method=True,
        )
        self.Drift = channel.unary_unary(
            "/slate.Cortex/Drift",
            request_serializer=slate__pb2.DriftRequest.SerializeToString,
            response_deserializer=slate__pb2.DriftResponse.FromString,
            _registered_method=True,
        )
        self.Commit = channel.unary_unary(
            "/slate.Cortex/Commit",
            request_serializer=slate__pb2.Trace.SerializeToString,
            response_deserializer=slate__pb2.Ack.FromString,
            _registered_method=True,
        )
        self.Reminisce = channel.unary_unary(
            "/slate.Cortex/Reminisce",
            request_serializer=slate__pb2.RecallRequest.SerializeToString,
            response_deserializer=slate__pb2.RecallResponse.FromString,
            _registered_method=True,
        )
        self.Consult = channel.unary_unary(
            "/slate.Cortex/Consult",
            request_serializer=slate__pb2.QueryRequest.SerializeToString,
            response_deserializer=slate__pb2.KnowledgeResponse.FromString,
            _registered_method=True,
        )
        self.Trigger = channel.unary_unary(
            "/slate.Cortex/Trigger",
            request_serializer=slate__pb2.ReflexRequest.SerializeToString,
            response_deserializer=slate__pb2.ExecutionResult.FromString,
            _registered_method=True,
        )
        self.DeleteRun = channel.unary_unary(
            "/slate.Cortex/DeleteRun",
            request_serializer=slate__pb2.RunRequest.SerializeToString,
            response_deserializer=slate__pb2.Ack.FromString,
            _registered_method=True,
        )


class CortexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Focus(self, request, context):
        """Flux"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Drift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Commit(self, request, context):
        """Echoes"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Reminisce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Consult(self, request, context):
        """Nexus"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Trigger(self, request, context):
        """Reflex"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteRun(self, request, context):
        """Management"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CortexServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Focus": grpc.unary_unary_rpc_method_handler(
            servicer.Focus,
            request_deserializer=slate__pb2.FocusRequest.FromString,
            response_serializer=slate__pb2.FocusResponse.SerializeToString,
        ),
        "Drift": grpc.unary_unary_rpc_method_handler(
            servicer.Drift,
            request_deserializer=slate__pb2.DriftRequest.FromString,
            response_serializer=slate__pb2.DriftResponse.SerializeToString,
        ),
        "Commit": grpc.unary_unary_rpc_method_handler(
            servicer.Commit,
            request_deserializer=slate__pb2.Trace.FromString,
            response_serializer=slate__pb2.Ack.SerializeToString,
        ),
        "Reminisce": grpc.unary_unary_rpc_method_handler(
            servicer.Reminisce,
            request_deserializer=slate__pb2.RecallRequest.FromString,
            response_serializer=slate__pb2.RecallResponse.SerializeToString,
        ),
        "Consult": grpc.unary_unary_rpc_method_handler(
            servicer.Consult,
            request_deserializer=slate__pb2.QueryRequest.FromString,
            response_serializer=slate__pb2.KnowledgeResponse.SerializeToString,
        ),
        "Trigger": grpc.unary_unary_rpc_method_handler(
            servicer.Trigger,
            request_deserializer=slate__pb2.ReflexRequest.FromString,
            response_serializer=slate__pb2.ExecutionResult.SerializeToString,
        ),
        "DeleteRun": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteRun,
            request_deserializer=slate__pb2.RunRequest.FromString,
            response_serializer=slate__pb2.Ack.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "slate.Cortex", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("slate.Cortex", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Cortex(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Focus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/slate.Cortex/Focus",
            slate__pb2.FocusRequest.SerializeToString,
            slate__pb2.FocusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Drift(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/slate.Cortex/Drift",
            slate__pb2.DriftRequest.SerializeToString,
            slate__pb2.DriftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Commit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/slate.Cortex/Commit",
            slate__pb2.Trace.SerializeToString,
            slate__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Reminisce(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/slate.Cortex/Reminisce",
            slate__pb2.RecallRequest.SerializeToString,
            slate__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Consult(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/slate.Cortex/Consult",
            slate__pb2.QueryRequest.SerializeToString,
            slate__pb2.KnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Trigger(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/slate.Cortex/Trigger",
            slate__pb2.ReflexRequest.SerializeToString,
            slate__pb2.ExecutionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteRun(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/slate.Cortex/DeleteRun",
            slate__pb2.RunRequest.SerializeToString,
            slate__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
